syntax = "proto3";

service Tasty {
    rpc Eat(Fruit) returns (TastyResponse) {}
}

enum FruitType {
    //"In proto3, the first value defined in an enum definition must have the value zero and should have the name ENUM_TYPE_NAME_UNSPECIFIED or ENUM_TYPE_NAME_UNKNOWN. "
    FRUIT_TYPE_UNSPECIFIED = 0;
    FRUIT_TYPE_APPLE = 1;
    FRUIT_TYPE_BANANA = 2;
    FRUIT_TYPE_ORANGE = 3;
}

message Fruit {
    FruitType fruit = 1;
}

message TastyResponse {
    FruitType fruit = 1;
    int32 tastiness = 2;
}


